package resource

func CoreResources() []Resource {
	return []Resource{
		{
			Name:         "contacts",
			Label:        "Contact",
			PluralLabel:  "Contacts",
			Module:       "crm",
			PermissionNS: "crm.contact",
			MutationMode: MutationModeCRUD,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "display_name", Label: "Name", Kind: FieldString, Required: true, Searchable: true, Sortable: true},
				{Name: "email", Label: "Email", Kind: FieldString, Searchable: true, Filterable: true},
				{Name: "phone", Label: "Phone", Kind: FieldString, Searchable: true},
				{Name: "owner_id", Label: "Owner", Kind: FieldUUID, Filterable: true},
				{Name: "lifecycle_stage", Label: "Lifecycle", Kind: FieldEnum, Filterable: true, Options: []string{"lead", "prospect", "customer", "inactive"}},
			},
			DefaultSort:   "display_name",
			DefaultSearch: []string{"display_name", "email", "phone"},
		},
		{
			Name:         "deals",
			Label:        "Deal",
			PluralLabel:  "Deals",
			Module:       "crm",
			PermissionNS: "crm.deal",
			MutationMode: MutationModeCommandsOnly,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "name", Label: "Name", Kind: FieldString, Required: true, Searchable: true, Sortable: true},
				{Name: "amount_minor", Label: "Amount", Kind: FieldMoney, Sortable: true},
				{Name: "stage_id", Label: "Stage", Kind: FieldUUID, Filterable: true},
				{Name: "owner_id", Label: "Owner", Kind: FieldUUID, Filterable: true},
				{Name: "status", Label: "Status", Kind: FieldEnum, Filterable: true, ReadOnly: true, Options: []string{"open", "won", "lost"}},
				{Name: "archived_at", Label: "Archived", Kind: FieldDateTime, Filterable: true, ReadOnly: true},
			},
			Actions: []Action{
				{Name: "move", Label: "Move stage", Permission: "crm.deal.move", Command: "crm.move_deal"},
				{Name: "win", Label: "Mark won", Permission: "crm.deal.win", Command: "crm.win_deal"},
				{Name: "lose", Label: "Mark lost", Permission: "crm.deal.lose", Command: "crm.lose_deal"},
				{Name: "reopen", Label: "Reopen", Permission: "crm.deal.reopen", Command: "crm.reopen_deal"},
				{Name: "archive", Label: "Archive", Permission: "crm.deal.archive", Command: "crm.archive_deal", Dangerous: true},
				{Name: "restore", Label: "Restore", Permission: "crm.deal.restore", Command: "crm.restore_deal"},
			},
			DefaultSort:   "updated_at",
			DefaultSearch: []string{"name"},
		},
		{
			Name:         "journal_entries",
			Label:        "Journal entry",
			PluralLabel:  "Journal entries",
			Module:       "finance",
			PermissionNS: "finance.journal",
			MutationMode: MutationModeCommandsOnly,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "number", Label: "Number", Kind: FieldString, Required: true, Searchable: true, Sortable: true, ReadOnly: true},
				{Name: "effective_date", Label: "Date", Kind: FieldDate, Required: true, Sortable: true, Filterable: true, ReadOnly: true},
				{Name: "currency", Label: "Currency", Kind: FieldString, Required: true, Filterable: true, ReadOnly: true},
				{Name: "description", Label: "Description", Kind: FieldText, Searchable: true, ReadOnly: true},
			},
			Actions: []Action{
				{Name: "post", Label: "Post journal", Permission: "finance.journal.post", Command: "finance.post_journal"},
				{Name: "reverse", Label: "Reverse journal", Permission: "finance.journal.reverse", Command: "finance.reverse_journal", Dangerous: true},
			},
			DefaultSort:   "effective_date",
			DefaultSearch: []string{"number", "description"},
		},
		{
			Name:         "sales_quotes",
			Label:        "Quote",
			PluralLabel:  "Quotes",
			Module:       "sales",
			PermissionNS: "sales.quote",
			MutationMode: MutationModeCommandsOnly,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "number", Label: "Number", Kind: FieldString, Searchable: true, Sortable: true, ReadOnly: true},
				{Name: "company_id", Label: "Company", Kind: FieldUUID, Filterable: true, ReadOnly: true},
				{Name: "currency", Label: "Currency", Kind: FieldString, Filterable: true, ReadOnly: true},
				{Name: "status", Label: "Status", Kind: FieldEnum, Filterable: true, ReadOnly: true, Options: []string{"draft", "sent", "accepted", "rejected", "expired"}},
				{Name: "total_minor", Label: "Total", Kind: FieldMoney, Sortable: true, ReadOnly: true},
				{Name: "valid_until", Label: "Valid until", Kind: FieldDate, Sortable: true, ReadOnly: true},
			},
			Actions: []Action{
				{Name: "create", Label: "New quote", Permission: "sales.quote.create", Command: "sales.create_quote", Collection: true},
				{Name: "send", Label: "Send", Permission: "sales.quote.send", Command: "sales.send_quote"},
				{Name: "accept", Label: "Accept", Permission: "sales.quote.accept", Command: "sales.accept_quote"},
				{Name: "reject", Label: "Reject", Permission: "sales.quote.reject", Command: "sales.reject_quote"},
				{Name: "expire", Label: "Expire", Permission: "sales.quote.expire", Command: "sales.expire_quote"},
			},
			DefaultSort:   "updated_at",
			DefaultSearch: []string{"number"},
		},
		{
			Name:         "sales_orders",
			Label:        "Sales order",
			PluralLabel:  "Sales orders",
			Module:       "sales",
			PermissionNS: "sales.order",
			MutationMode: MutationModeCommandsOnly,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "number", Label: "Number", Kind: FieldString, Searchable: true, Sortable: true, ReadOnly: true},
				{Name: "quote_id", Label: "Quote", Kind: FieldUUID, Filterable: true, ReadOnly: true},
				{Name: "status", Label: "Status", Kind: FieldEnum, Filterable: true, ReadOnly: true, Options: []string{"confirmed", "fulfilled", "cancelled"}},
				{Name: "total_minor", Label: "Total", Kind: FieldMoney, Sortable: true, ReadOnly: true},
			},
			Actions: []Action{
				{Name: "fulfill", Label: "Fulfill", Permission: "sales.order.fulfill", Command: "sales.fulfill_order"},
				{Name: "cancel", Label: "Cancel", Permission: "sales.order.cancel", Command: "sales.cancel_order", Dangerous: true},
			},
			DefaultSort:   "updated_at",
			DefaultSearch: []string{"number"},
		},
		{
			Name:         "invoices",
			Label:        "Invoice",
			PluralLabel:  "Invoices",
			Module:       "invoicing",
			PermissionNS: "sales.invoice",
			MutationMode: MutationModeCommandsOnly,
			TenantScoped: true,
			Audited:      true,
			Fields: []Field{
				{Name: "number", Label: "Number", Kind: FieldString, Searchable: true, Sortable: true, ReadOnly: true},
				{Name: "order_id", Label: "Order", Kind: FieldUUID, Filterable: true, ReadOnly: true},
				{Name: "currency", Label: "Currency", Kind: FieldString, Filterable: true, ReadOnly: true},
				{Name: "status", Label: "Status", Kind: FieldEnum, Filterable: true, ReadOnly: true, Options: []string{"draft", "issued", "paid", "void"}},
				{Name: "total_minor", Label: "Total", Kind: FieldMoney, Sortable: true, ReadOnly: true},
			},
			Actions: []Action{
				{Name: "issue", Label: "Issue", Permission: "sales.invoice.issue", Command: "sales.issue_invoice"},
				{Name: "mark_paid", Label: "Mark paid", Permission: "sales.invoice.mark_paid", Command: "sales.mark_invoice_paid"},
				{Name: "void", Label: "Void", Permission: "sales.invoice.void", Command: "sales.void_invoice", Dangerous: true},
			},
			DefaultSort:   "updated_at",
			DefaultSearch: []string{"number"},
		},
	}
}
